version: '3.9'

services:
  postgres-db-casbin:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=casbin
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - testuzb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-service:
    container_name: api-gateway
    build: .
    depends_on:
      postgres-db-casbin:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
     - sales
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  testuzb:
    name: testuzb
    driver: bridge
    external: true

volumes:
  db:
